name: remix_icons_flutter
description: A Remix Icon library package for Flutter applications.
version: 4.7.0-beta.1
homepage: https://github.com/Remix-Design/RemixIcon
repository: https://github.com/vqh2602/lucide-flutter-main

environment:
  sdk: ^3.0.0
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^4.1.0
  lint: ^2.8.0

flutter:
  fonts:
    - family: RemixIcon
      fonts:
        - asset: assets/remixicon.ttf
# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: Lucide Logo
    path: screenshots/logo.png

topics:
  - remix-icon
  - remixicon
  - icons
  - flutter-icons
